<%@ Page Title="" Language="C#" MasterPageFile="~/BackUp/MainPage.master" %>

<script runat="server">

    protected void Button1_Click(object sender, EventArgs e)
    {
        DetailsView1.Visible = true;
        DetailsView1.ChangeMode(DetailsViewMode.Insert);
    }

    protected void DetailsView1_ItemInserted(object sender, DetailsViewInsertedEventArgs e)
    {
        GridView1.DataBind();
        DetailsView1.Visible = false;
    }

    protected void Parents_Updated(object sender, SqlDataSourceStatusEventArgs e)
    {
        if (e.Exception == null)
        {
            GridView1.DataBind();
            DetailsView1.Visible = false;
        }else
        {
            Label1.Text = e.Exception.Message;
            e.ExceptionHandled = true;
        }
    }
</script>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />    <p>&nbsp;<a href="BackDataSource.aspx">基本資料</a>:<a href="ParentsData.aspx">親人資料</a>:<a href="OtherHealth.aspx">煙癮資料</a></p>
    <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateRows="False" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" DataKeyNames="MemberId" DataSourceID="Parents" GridLines="Vertical" Height="50px" Width="125px" OnItemInserted="DetailsView1_ItemInserted" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True">
        <AlternatingRowStyle BackColor="#DCDCDC" />
        <EditRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
        <Fields>
            <asp:BoundField DataField="FatherName" HeaderText="FatherName" SortExpression="FatherName" />
            <asp:BoundField DataField="MotherName" HeaderText="MotherName" SortExpression="MotherName" />
            <asp:BoundField DataField="MemberId" HeaderText="MemberId" ReadOnly="True" SortExpression="MemberId" />
            <asp:BoundField DataField="BloodType" HeaderText="BloodType" SortExpression="BloodType" />
        </Fields>
        <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
        <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
        <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
    </asp:DetailsView>
    <asp:SqlDataSource ID="Parents" runat="server" ConnectionString="<%$ ConnectionStrings:HealthSiteConnectionString2 %>" DeleteCommand="DELETE FROM [Parents] WHERE [MemberId] = @MemberId" InsertCommand="INSERT INTO [Parents] ([FatherName], [MotherName], [MemberId], [BloodType]) VALUES (@FatherName, @MotherName, @MemberId, @BloodType)" SelectCommand="SELECT * FROM [Parents] ORDER BY [MemberId]" UpdateCommand="UPDATE [Parents] SET [FatherName] = @FatherName, [MotherName] = @MotherName, [BloodType] = @BloodType WHERE [MemberId] = @MemberId" OnUpdated="Parents_Updated">
        <DeleteParameters>
            <asp:Parameter Name="MemberId" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="FatherName" Type="String" />
            <asp:Parameter Name="MotherName" Type="String" />
            <asp:Parameter Name="MemberId" Type="Int32" />
            <asp:Parameter Name="BloodType" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="FatherName" Type="String" />
            <asp:Parameter Name="MotherName" Type="String" />
            <asp:Parameter Name="BloodType" Type="String" />
            <asp:Parameter Name="MemberId" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="MemberId" DataSourceID="Parents" ForeColor="Black" GridLines="Horizontal">
        <Columns>
            <asp:CommandField ShowDeleteButton="True" />
            <asp:BoundField DataField="FatherName" HeaderText="FatherName" SortExpression="FatherName" />
            <asp:BoundField DataField="MotherName" HeaderText="MotherName" SortExpression="MotherName" />
            <asp:BoundField DataField="MemberId" HeaderText="MemberId" ReadOnly="True" SortExpression="MemberId" />
            <asp:BoundField DataField="BloodType" HeaderText="BloodType" SortExpression="BloodType" />
        </Columns>
        <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
        <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
        <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F7F7F7" />
        <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
        <SortedDescendingCellStyle BackColor="#E5E5E5" />
        <SortedDescendingHeaderStyle BackColor="#242121" />
    </asp:GridView>
    <asp:Label ID="Label1" runat="server"></asp:Label>
    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="新增" />
    </asp:Content>

