//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class HealthSiteEntities3 : DbContext
{
    public HealthSiteEntities3()
        : base("name=HealthSiteEntities3")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<member> members { get; set; }
    public virtual DbSet<Membership> Memberships { get; set; }
    public virtual DbSet<OtherHealthBar> OtherHealthBars { get; set; }
    public virtual DbSet<Parent> Parents { get; set; }
}
