//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class member
{
    public string username { get; set; }
    public string hashpassword { get; set; }
}

public partial class Membership
{
    public int MemberId { get; set; }
    public Nullable<int> SleepHour { get; set; }
    public int Weight { get; set; }
    public int Height { get; set; }
    public Nullable<int> Waistline { get; set; }
    public int DailyJogPath { get; set; }
    public string MemberName { get; set; }
    public string Sex { get; set; }
    public Nullable<System.DateTime> Birthday { get; set; }
    public int BMR { get; set; }
    public int FER { get; set; }
    public int REE { get; set; }
}

public partial class OtherHealthBar
{
    public int MemberId { get; set; }
    public Nullable<int> Addiction { get; set; }
    public System.DateTime Today { get; set; }
    public Nullable<int> HDC_mg_dl_ { get; set; }

    public virtual OtherHealthBar OtherHealthBar1 { get; set; }
    public virtual OtherHealthBar OtherHealthBar2 { get; set; }
}

public partial class Parent
{
    public string FatherName { get; set; }
    public string MotherName { get; set; }
    public int MemberId { get; set; }
    public string BloodType { get; set; }
}
